### PR TITLE
add setDefaultProps feature

### PR DESCRIPTION
**Pull request by adminy**
Addressing #63 issue.

### CODE REVIEW

**Comment by Kir-Antipov** [comment]
... Why? This is ugly. Do you realize what kind of disaster is this mutable global state with a whole bunch of side effects?

**Comment by adminy** [comment]
Depends on how you use it.

**Comment by adminy** [comment]
I think that its an important feature none-the-less as passing something to every component through window is even uglier, and its not like there is a connect api in place here.

**Comment by Kir-Antipov** [comment]
> its not like there is a connect api in place here

Of course not. `jsx-dom` is NOT React replacement. It does NOT create components. Its sole purpose is to create a bridge between jsx and **plain** DOM elements. No more, no less. So, if you need React-specific features, state management and so on, please, use React.

> I think that its an important feature

Even if this were true, it's still a very ugly solution. But it's not really. If you need to pass some value to your child "components"... just do so?

I do not see how can this disaster:
```jsx
React.setDeafaultProps({value: 15});

function Parent() {
  return <Child />;
}

function Child({value}) {
  return <div>{value}</div>;
}
```

be better than this nice and strait-forward approach:

```jsx
function Parent({value}) {
  return <Child value={value} />;
}

function Child({value}) {
  return <div>{value}</div>;
}
```

**Comment by adminy** [comment]
> be better than this nice and strait-forward approach:

Actually this is kind of the problem. You assume its a single parent and single component issue. But once you have a large system with lots of components and lots of sub sub children its quite the hell passing in every argument you need every single time. suppose you want to pass in theme parameters to all the components through higher order components. Its really a big help if you can mask away all the variable passing with just a function call.

You don't have to document it but at least expose the api for this possibility.

**Comment by zenflow** [comment]
> ... Why? This is ugly. Do you realize what kind of disaster is this mutable global state with a whole bunch of side effects?

Strongly agree. This totally disregards the principles of Functional Programming.

> Actually this is kind of the problem. You assume its a single parent and single component issue. But once you have a large system with lots of components and lots of sub sub children its quite the hell passing in every argument you need every single time. suppose you want to pass in theme parameters to all the components through higher order components. Its really a big help if you can mask away all the variable passing with just a function call.

@adminy I don't think this was an assumption of @Kir-Antipov. The example is just a minimalistic example of how you can do it instead. Yes, it's a little more verbose, but it's completely explicit and clear. There can be no mystery about where the value of `value` comes from.

I see your issue though. Why not just this? .. 

```jsx
const value = 15;

function Parent() {
  return <Child />;
}

function Child() {
  return <div>{value}</div>;
}

const parent = <Parent />;
```

You can even define that in another module, export it, and import it in whatever component modules you need.

> Another thing to consider is that the parent might not need that value at all! maybe its just a sub-child component that needs value.

That's fine. The example actually shows that.. `Parent` only needs that value so it can pass it to `Child`.

**Comment by adminy** [comment]
Having a global variable might be a solution for certain scenarios, however if the data comes from the server or it needs to be modified by a store procedure then it has to come accessible to both places. But its an alternative I'm considering.

**Comment by adminy** [comment]
Another example is having an emit function accessible to all components.
This isn't breaking anything, its a harmless but very useful feature.

**Comment by proteriax** [comment]
Functional components in `jsx-dom` already support `defaultProps`, you might want to use that instead.

**Comment by adminy** [comment]
defaultProps is for a specific component. it does not apply to all components. also I don't think the arrow function version supports it.

**Comment by proteriax** [comment]
Then you want a global variable. I’m leaning towards not merging this because once you have two libraries that both use `jsx-dom` and apply different things to *all* components, chaos will ensure.

**Pull request closed without merging**
