### PR TITLE
Added support for Class Components

### PR DESCRIPTION
**Pull request by Kir-Antipov**
The idea of the pull request is indicated in the title: now `jsx-dom` supports class components:

```jsx
import React from "jsx-dom";

class Welcome extends React.Component {
  render() {
    return <h1>Hello, {this.props.name}</h1>;
  }
}
```

Class components are really useful when it comes to inheritance (similar codebase, slightly modified markup with the same logic and so on). Also class-syntax helps to organize component logic in one place

P.S. - huge thanks for this library as it is the best of its kind :)

### CODE REVIEW

**Comment by zenflow** [comment]
But why not just ...?

```jsx
function Welcome (props) {
  return <h1>Hello, {props.name}</h1>;
}
```

What's the point of adding a 2nd (more complicated) way of writing components for jsx-dom?

**Comment by Kir-Antipov** [comment]
@zenflow, as I mentioned in the description, the main reason is inheritance. My general example is... too general, it just had to show what the simplest class component looks like (and the simplest class component can easily be rewritten into a functional component) ¯\\_(ツ)_/¯

Not such general example:

```jsx
class Button extends React.Component {
  onClick(e) {
    console.log("click");
  }

  onDoubleClick(e) {
    console.log("double click");
  }

  render() {
    return (
      <button onClick={this.onClick} onDblClick={this.onDoubleClick}>
        {this.props.text}
      </button>
    );
  }
}

class CoolerButton extends Button {
  onClick(e) {
    e.preventDefault();
    super.onClick(e);
    console.log("and it was cool click");
  }
}
```

This example can no longer be rewritten into a functional component (without pain, of course)

**Comment by zenflow** [comment]
> as I mentioned in the description, the main reason is inheritance. 

@Kir-Antipov lol looks like I posted my comment at the exact same minute you added the motivation to the PR description.
Sorry to make you do a full explicit explanation.
Yeah I think that's a really good reason to have class components here. 👍

**Comment by Kir-Antipov** [comment]
@zenflow, no worries, should have posted this explanation initially :D

**Comment by proteriax** [comment]
Published as `jsx-dom@7.0.0-beta.0`.

**Pull request merged**
